### ISSUE TITLE
Display model state in search results

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-annotation-review#13]
It would be helpful for curators to know, when they're searching for models, what the model state is, e.g. state=production, state=development, etc.

Can this be displayed as metadata in the line for each model in the search results?

Note that this information is available on the current landing page.

Thx.

**Comment by tmushayahama** [comment]
Search results now showing model state

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
I can see models that have 4/5 possible states (delete, development, production, review) with none returned for closed (as expected).
The number of models returned doesn't always match what I see on noctua.geneontology.org, though.
For example, on noctua.geneontology.org, I can see eight models that have state=review, but when I filter for state=review I get six models.
Is this just a matter of what models set is being searched?
Thx.

**Comment by vanaukenk** [comment]
Need to test that search numbers return the correct number of models in any given state.

**Comment by vanaukenk** [comment]
See: https://github.com/geneontology/minerva/issues/235

Due to the large number of models and the fact that we want a count without pagination, we think the counts should be computed on the server, i.e. minerva.

It could also be done as a separate query.

**Comment by vanaukenk** [comment]
This is implemented on the new Noctua landing page, so I am closing the ticket.
