### ISSUE TITLE
Alphabetize list in 'Filter by Group'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-annotation-review#17]
@tmushayahama 
Can the groups in the 'Filter by Group' list be sorted alphabetically?
This makes it much easier to find the group(s) you're looking for.

Thanks!

**Comment by tmushayahama** [comment]
This was fixed on landing page

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
I'll close this ticket.
