### ISSUE TITLE
Search must cover all aspects of GO - MF, BP, and CC

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-annotation-review#2]
The search for MF works fine, but I'm unable to search for a BP or CC term.

**Comment by tmushayahama** [comment]
@vanaukenk now this is working. Is it a duplicate of https://github.com/geneontology/noctua-annotation-review/issues/7 or different

**Comment by vanaukenk** [comment]
Yes, this is working now; thanks.
This issue isn't a duplicate of #7 , so I think we can close this one.
