### ISSUE TITLE
Modifications to initial ART prototype

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-annotation-review#30]
Based on 2020-09-30 and 2020-10-02 workbenches calls:

@tmushayahama Here's what I have on my list.  I've tried to check off ones you've already addressed.

Feel free to add more if I've missed anything.  Thanks!

- [x] Remove toggle button to the right of Annotation Review Tool

- [x] Replace Annotation Review Tool text with just Annotation Review in menu option

- [x] Indicate that Annotation Review mode is activated by changing background color of menu option

- [x] Move number of models selected to first box in the workflow 

- [x] Rename workflow boxes (from L to R): Search, Review, Checkout with appropriate subtext, 'Add/remove models'; 'Edit models'; 'Review and submit changes' ( @tmushayahama - I didn't take a screenshot of your development site today, so didn't quite remember what the current subtext is.)

- [x] Debug horizontal scrollbar not always appearing at the bottom of the table

- [x] Debug table behavior so that clicking the number sequence or up/down arrows moves the results table in the correct order

- [x] Move Cancel - Reset - Review Changes buttons from table to bottom of look-up page

- [x] Change actions buttons at the bottom of the ART lookup page to be:  Clear List - Undo Changes - Review Changes

- [x] Remove 'CAMs' row from change summary table

- [x] Upon submission of changes, clear the basket and go back to the default landing page setting with the Search workbench open

**Comment by vanaukenk** [comment]
- [x] Change position/order when new models are added so that the newest added (wrt time) is at the bottom, rather than the top, of the list in the review table

- [x] Change numbering of matches in the annotation review box to start from 1

- [x] When stepping through results, have the table scroll so that the activity unit (or BP or CC only) is at the top of the table field

- [x] Sort matching search results in the table so that as users step through the results the order matches how the results are presented in the table

**Comment by vanaukenk** [comment]
- [x] Add arrows to go to the first match or the last match

- [x] Add horizontal scroll bar back to table

- [x] If the curator attempts to remove a model that has pending changes from the list, create a pop-up to ask them if they want to save the changes, reset, or cancel remove model.  If no pending changes, confirm that they want to remove the model.

- [x] Add scroll bar to ontology field to see longer terms

- [x] When curator clicks on the Review Changes box, display from the top of the box down

**Comment by tmushayahama** [comment]
@vanaukenk @lpalbou for model errors, I can only get it after I have opened the model. There is no minerva functionality on this. It would be nice to have a flag for this on the initial search results.

**Comment by vanaukenk** [comment]
Thanks for the update @tmushayahama 
I agree that it'd be helpful to have a flag for models with errors.  We can discuss further on one of our workbenches calls.

I also update this ticket  https://github.com/geneontology/noctua-landing-page/issues/32 with your comment above.

**Comment by vanaukenk** [comment]
A few additional tweaks after discussion on the 2020-12-16 workbenches call:

- [x] Add a pop-up window to alert curators if they have unsaved work before logging out.  The pop-up window would give them the option to NOT save any changes and clear the selected list, OR return to the ART workbench to review and save their changes.
- [x] This is more of a landing page thing - remove the vertical line connecting the numbers between models; keep the vertical line for numbers within models, e.g. 1.1 and 1.2.  @tmushayahama - only make this change if it's not a big investment of time.
- [x] As curators step through the ART workflow, add a green background to the active box, i.e. Search, Review, Checkout, to help curators keep better track of where they are in the process.
- [x] Remove the node ids from the table display of models being reviewed

**Comment by lpalbou** [comment]
>  I can only get it after I have opened the model. There is no minerva functionality on this. It would be nice to have a flag for this on the initial search results.

Right, I remember that you mentioned that. While a tag should be computed per model every time it's saved, it's not done at the moment. Question: on a single page, you are showing 50 models at once. For the time being, how about having a async process running in the background and opening those models so 1) it's not blocking the UI 2) you could still display that information in the meantime ? The trick is obviously to stop that async process every time there is a new search or someone changes the pagination

**Comment by vanaukenk** [comment]
From 2021-02-19 workbenches call, priorities for development before release to production:

- [x] 1. Reconcile model search results as displayed in 'Results' vs actually enumerated in the table (this is an [NLP issue](https://github.com/geneontology/noctua-landing-page/issues/33)) - Note this ticket has been transferred to the minerva tracker: https://github.com/geneontology/minerva/issues/370

- [x] 2. Optimize diff behavior, if possible, to implement and display changes on large models more quickly - Laurent-Philippe and Tremayne will discuss further what options we have for improving the response time for the user

- [x] 3. Add a pop-up window or some other indication that an action has been sent to the server and is being processed; otherwise curators will wonder if there's something wrong (the 'Relax' pop-up on the graph editor could be re-used here) - Tremayne has implemented a waiting bar to indicate that there is action behind the scenes

- [x] 4. Align stepping through matched search results with scrolling behavior on the table, i.e. when stepping through individuals to make an edit,  1-> 2->3, have the table scroll to the next matched individual so curators don't lose track of where they are in the editing process.
- [x] 5. Check table headings display so that text for different columns is not overlapping, e.g. ASP and TERM
- [x] 6. Check that number returned on the left-hand editing table reflects the actual number in the selected models.

@lpalbou @tmushayahama @ukemi - please add or edit the above if needed for clarity.  Thx.
