### ISSUE TITLE
Clear button in search box not working

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-annotation-review#4]
The Clear button in the search box does not seem to be working to clear any value.  

It just seems to restore the generic label, e.g. Go Term, when the field is empty.

**Comment by vanaukenk** [comment]
@tmushayahama - revisiting this ticket.  

The clear button now clears the search inputs, but also closes the search box, so the user has to click on the search icon again to start a new search.

It would be better if 'Clear' just cleared the inputs in the search box(es) but left the search window open.

Thx.

**Comment by vanaukenk** [comment]
Ideally, it would be possible to either clear all or clear one or more input boxes individually.

**Comment by vanaukenk** [comment]
@tmushayahama 
I'm trying to test this, but it seems that now after I've selected a search term and click on 'Search' the search term is cleared from the box, so I can no longer see what I'm searching on and then test if clicking on 'Clear' removes it from the box.
Clicking on 'Clear' does still keep the search widget open, though, so that is now working as expected.

**Comment by tmushayahama** [comment]
@vanaukenk I realized that I had put the clear functionality after search button is clicked. Now I see the problem of editing a box after search.  I will remove the clear after search. The other part is the filter drawer/panel idea was to serve it as a search summary as well and the search panel for new input only. Should I add search summary as well on the search drawer? Where do you think?

Filter Panel/Drawer
![image](https://user-images.githubusercontent.com/2273929/58722066-5d44e600-838b-11e9-9b91-90cbd94b63ee.png)

**Comment by vanaukenk** [comment]
@tmushayahama 
Yes, I think a search summary would be really helpful to curators.
Can we fit it across the top of the table where the 'Filtered by' text currently is?

**Comment by vanaukenk** [comment]
@tmushayahama 
For clearing the filter boxes, it looks like clicking on the 'x' clears the selected value, but not the original text I typed in.  Can clicking on the 'x' clear the entire box?  Otherwise, the curators will need to additionally remove their typing.  

I see the same thing when I clikc on the 'Clear' button at the bottom of the list of filters.

Thx.

![image](https://user-images.githubusercontent.com/1730534/58831717-4b797200-861b-11e9-8fd7-72326393f2db.png)

![image](https://user-images.githubusercontent.com/1730534/58831740-58966100-861b-11e9-837f-90bc164b153f.png)

**Comment by pgaudet** [comment]
This seems to work for me

Ca we close @vanaukenk ?

**Comment by vanaukenk** [comment]
This one is done.
